'''jinja2 - sandbox mode for security
    pip install sdk generator

    pyproject.toml
    init file
    py module per suggested module
'''

from __future__ import annotations

import os
from pathlib import Path
from typing import List, Dict, Optional
from jinja2 import Environment, FileSystemLoader, BaseLoader, DictLoader, TemplateNotFound, select_autoescape
from jinja2.sandbox import SandboxedEnvironment

_PYPROJECT_TEMPLATE = """\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{{ package_name }}"
version = "{{ version }}"
description = "Auto-generated SDK from DevDNA pattern library"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "DevDNA", email = "devdna@local"},
]

[project.urls]
Homepage = "https://github.com/yourusername/{{ package_name }}"

[tool.hatch.build.targets.wheel]
packages = ["{{ package_name }}"]
"""

_README_TEMPLATE = """\
# {{ package_name | title }}

Auto-generated Python SDK from your DevDNA pattern library.

## Modules

{% for module, functions in modules.items() %}
### `{{ module }}`

{% for f in functions %}
- `{{ f.function_name }}` — {{ f.description or "No description" }}
{% endfor %}
{% endfor %}

## Installation

```bash
cd {{ output_path }}
pip install -e .

from {{ package_name }} import *
"""

_MODULE_TEMPLATE = '''
    """
    {{ module_name | title }} module.

    Auto generated by DevDNA, review before production use.
    """

    {% for pattern in patterns %}
    {{pattern.implementation}}

    {%endfor%}
'''

_INIT_TEMPLATE = '''
    """
    {{ package_name |title }} - Auto-generated DevDNA SDK.

    """

    {%for module, in modules%}
        from .{{ module }} import *
    {%endfor%}

    all = [
    {%for name in exports%}
        "{{ name }}",
    {%endfor%}
    ]
'''


class SDKGenerator:
    def __init__(self, package_name: str = "devdna_sdk", output_dir: Optional[Path] = None, version: str = "0.1.0") -> None:
        self.package_name = package_name
        self.output_dir = output_dir or Path.home() / ".devdna"/ "sdk"
        self.version = version

        #sandboxed
        self.env = SandboxedEnvironment()