"""
SDK Generator — turns accepted patterns into a real pip-installable Python package.

Uses Jinja2 with sandbox mode for security. Generates:
  - pyproject.toml
  - README.md with module docs
  - __init__.py with public exports
  - One .py module per suggested_module (with auto-detected imports)
"""

from __future__ import annotations

import re
import textwrap
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional

from jinja2.sandbox import SandboxedEnvironment
from jinja2 import DictLoader

from devdna.core.memory import StoredPattern


# =============================================================================
# JINJA2 TEMPLATES (rendered into generated SDK files)
# =============================================================================

_TEMPLATES = {
    "pyproject.toml": """[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{{ package_name }}"
version = "{{ version }}"
description = "Auto-generated SDK from DevDNA pattern library"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{name = "DevDNA User"}]
{% if dependencies %}
dependencies = [
{% for dep in dependencies %}
    "{{ dep }}",
{% endfor %}
]
{% endif %}

[tool.hatch.build.targets.wheel]
packages = ["{{ package_name }}"]
""",

    "README.md": """# {{ package_name | title }}

Auto-generated Python SDK from your DevDNA pattern library.

## Modules
{% for module, functions in modules.items() %}
### `{{ module }}`
{% for f in functions %}
- `{{ f.function_name }}` — {{ f.description or "No description" }}
{% endfor %}
{% endfor %}

## Installation
```bash
cd {{ output_path }}
pip install -e .
```

## Usage
```python
from {{ package_name }} import some_function
```
""",

    "module.py": '''
from __future__ import annotations

"""
{{ module_name | title }} module.

Auto-generated by DevDNA. Review before production use.
"""

{% for imp in imports %}
{{ imp }}
{% endfor %}

{% for pattern in patterns %}
{{ pattern.implementation }}
{% endfor %}
''',

    "__init__.py": '''"""
{{ package_name | title }} -- Auto-generated DevDNA SDK.
"""

{% for module in modules %}
from .{{ module }} import *
{% endfor %}

__all__ = [
{% for name in exports %}
    "{{ name }}",
{% endfor %}
]
''',
}


# =============================================================================
# GENERATOR
# =============================================================================

class SDKGenerator:
    """
    Generates a real Python package from accepted patterns.

    Usage:
        gen = SDKGenerator(package_name="my_sdk")
        path = gen.generate(patterns)
        print(f"SDK ready at {path}")
        print(f"Install: pip install -e {path}")
    """

    # Modules to auto-detect and import in generated files
    _STDLIB_MODULES = [
"logging", "os", "sys", "json", "re", "pathlib", "typing",
"datetime", "collections", "itertools", "functools", "math",
"random", "hashlib", "base64", "urllib", "http", "email",
"csv", "io", "pickle", "copy", "inspect", "warnings",
"contextlib", "enum", "dataclasses", "abc",
]
    _DEP_MAP = {
    "pd": "pandas", "pandas": "pandas",
    "np": "numpy", "numpy": "numpy",
    "requests": "requests",
    "pydantic": "pydantic",
    "sqlalchemy": "sqlalchemy",
    "httpx": "httpx",
    "boto3": "boto3",
    "fastapi": "fastapi",
    "flask": "flask",
    "django": "django",
}

    def __init__(
        self,
        package_name: str = "devdna_sdk",
        output_dir: Optional[Path] = None,
        version: str = "0.1.0",
    ) -> None:
        self.package_name = package_name
        self.output_dir = output_dir or Path.home() / ".devdna" / "sdk"
        self.version = version

        # Sandboxed: LLM output is untrusted until human review
        self.env = SandboxedEnvironment(
            loader=DictLoader(_TEMPLATES),
            autoescape=False,  # Generating Python, not HTML
        )

    def generate(self, patterns: List[StoredPattern]) -> Path:
        """
        Generate the complete SDK package.

        Args:
            patterns: List of StoredPattern with status='accepted'

        Returns:
            Path to the generated package root.

        Raises:
            ValueError: If no patterns provided.
        """
        if not patterns:
            raise ValueError(
                "No accepted patterns provided. Run `devdna review` first."
            )

        # Group by sanitized module name
        modules: Dict[str, List[StoredPattern]] = defaultdict(list)
        for p in patterns:
            modules[self._sanitize_module(p.suggested_module)].append(p)

        #detect third party imports
        third_party_deps = self._detect_dependencies(patterns)

        # Create package directory (pip install expects this structure)
        pkg_dir = self.output_dir / self.package_name
        pkg_dir.mkdir(parents=True, exist_ok=True)

        # --- Project-level files ---
        (self.output_dir / "pyproject.toml").write_text(
            self.env.get_template("pyproject.toml").render(
                package_name=self.package_name,
                version=self.version,
                dependencies=third_party_deps
            ),
            encoding="utf-8",
        )

        (self.output_dir / "README.md").write_text(
            self.env.get_template("README.md").render(
                package_name=self.package_name,
                modules=modules,
                output_path=self.output_dir,
            ),
            encoding="utf-8",
        )

        # --- Package-level files ---
        exports: List[str] = []
        for module_name, module_patterns in sorted(modules.items()):
            # Dedent implementations so 'def' starts at column 0
            dedented_patterns = []
            for p in module_patterns:
                clean_impl = textwrap.dedent(p.implementation).strip()
                dedented_patterns.append(
                    p.__class__(
                        id=p.id,
                        function_name=p.function_name,
                        signature=p.signature,
                        implementation=clean_impl,
                        suggested_module=p.suggested_module,
                        description=p.description,
                        confidence_reasoning=p.confidence_reasoning,
                        source_hash=p.source_hash,
                        example_count=p.example_count,
                        status=p.status,
                        created_at=p.created_at,
                        reviewed_at=p.reviewed_at,
                    )
                )

            # Auto-detect imports needed by this module's functions
            imports = self._extract_stdlib_imports(
                [p.implementation for p in dedented_patterns]
            )

            (pkg_dir / f"{module_name}.py").write_text(
                self.env.get_template("module.py").render(
                    module_name=module_name,
                    patterns=dedented_patterns,
                    imports=imports,
                ),
                encoding="utf-8",
            )
            exports.extend(p.function_name for p in module_patterns)

        (pkg_dir / "__init__.py").write_text(
            self.env.get_template("__init__.py").render(
                package_name=self.package_name,
                modules=sorted(modules.keys()),
                exports=sorted(set(exports)),
            ),
            encoding="utf-8",
        )

        return self.output_dir

    @staticmethod
    def _sanitize_module(name: str) -> str:
        """
        Convert any string to a valid Python module name.
        'API Client' -> 'api_client'
        'data-utils' -> 'data_utils'
        """
        cleaned = name.lower().strip()
        for char in ["-", " ", "."]:
            cleaned = cleaned.replace(char, "_")
        cleaned = "".join(
            c if c.isalnum() or c == "_" else "_" for c in cleaned
        )
        while "__" in cleaned:
            cleaned = cleaned.replace("__", "_")
        return cleaned.strip("_")

    def _extract_stdlib_imports(self, implementations: List[str]) -> List[str]:
        """
        Auto-detect common module imports from implementation code.

        Scans for `module.attr` usage and adds `import module` statements.
        Handles aliases like `pd` -> `import pandas`.
        """
        imports = set()

        for impl in implementations:
            for module in self._STDLIB_MODULES:
                # Match module.attr or module.function() usage
                if re.search(rf'\b{re.escape(module)}\.', impl):
                    imports.add(f"import {module}")
        return sorted(imports)

    def _detect_dependencies(self, patterns: List[StoredPattern]) -> List[str]:
        """Extract third-party dependencies from implementations."""        
        found = set()
        for p in patterns:
            for alias, package in self._DEP_MAP.items():
                if re.search(rf'\b{re.escape(alias)}\.', p.implementation):
                    found.add(package)
        return sorted(found)